---
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  ruby: circleci/ruby@2.0.1

commands:

  bundle_install:
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      # - ruby/install-deps
      - run:
          name: Bundle install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          key: github-ci-prototype-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    working_directory: &root '~/github-cli-prototype'
    docker:
      - image: cimg/ruby:3.2
    executor: ruby/default
    steps:
      - attach_workspace:
          at: *root
      - bundle_install
      - persist_to_workspace:
          root: *root
          paths:
            - '*'
  test:
    working_directory: *root
    docker:
      - image: cimg/ruby:3.2
    executor: ruby/default
    steps:
      - attach_workspace:
          at: *root
      - bundle_install
      - run:
          name: Run the RSpec test suites
          command: bundle exec rspec
      - persist_to_workspace:
          root: *root
          paths:
            - "*"
      - store_artifacts:
          path:
            ~/github-cli-prototype/coverage
          destination:
            coverage

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  ci: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - test:
          requires:
            - build

